# Generated by Django 5.0.6 on 2024-07-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product_Details",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=25, unique=True)),
                ("category", models.CharField(max_length=50, unique=True)),
                ("price", models.IntegerField()),
                ("description", models.TextField()),
                (
                    "sizes",
                    models.CharField(
                        choices=[
                            ("XXL", "double extra large"),
                            ("XL", "extra large"),
                            ("L", "large"),
                            ("M", "medium"),
                            ("S", "small"),
                            ("XXXl", "triple extra large"),
                        ],
                        max_length=20,
                    ),
                ),
                ("colour", models.CharField(max_length=20)),
                ("fabric", models.CharField(max_length=20)),
                (
                    "preferred_season",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
    ]
