# Generated by Django 5.0.6 on 2024-07-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product_details",
            name="category",
            field=models.CharField(max_length=50),
        ),
    ]
