# Generated by Django 5.0.6 on 2024-07-16 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_details_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product_details",
            name="is_deleted",
        ),
    ]
